AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Poc 
Resources:
  ElasticacheCluster:  
    Type: AWS::ElastiCache::CacheCluster
    Properties: 
      AutoMinorVersionUpgrade: No
      AZMode: single-az
      CacheNodeType: cache.t3.medium
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: redis
      EngineVersion: 5.0.0
      NumCacheNodes: 1    
      VpcSecurityGroupIds:
      - !GetAtt 
        - ElasticacheSecurityGroup
        - GroupId
      Port: 6379
      PreferredMaintenanceWindow: sun:23:00-mon:01:30
  SubnetGroup:
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties: 
      CacheSubnetGroupName: SubnetGroup
      Description: Teste subnet
      SubnetIds: 
        - subnetA #trocar por uma subnet da sua conta
        - subnetB #trocar por uma subnet da sua conta
  ElasticacheSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Elasticache Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 11211
          ToPort: 11211
          SourceSecurityGroupName: Default
